version: '3.7'

services:
  counting:
    container_name: counting
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - prod=false
    expose:
      - '4000'
    ports:
      - '4010:4000'
      - '27017:27017'
    command: npm run start