version: '3.7'

services:
  counting:
    container_name: counting
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - COUNTING_PROD=true
      - DB_HOST=192.168.1.108
      - DB_USER=<USERNAME>
      - DB_PASS=<PASSWORD>
    expose:
      - '4000'
    ports:
      - '4010:4000'
      - '27017:27017'
    command: npm run start